-- ====================================================================
-- SCRIPT DDL: MVP de Segmentación B2B - Oracle Autonomous Database
-- ====================================================================

-- 1. TABLAS OFICIALES (SRI Y SCVS)
-- ====================================================================

-- 1.1 Resumen de RUCs del SRI
CREATE TABLE SRI_RUC_EMPRESAS_RESUMEN (
    RUC VARCHAR2(13) PRIMARY KEY,
    RAZON_SOCIAL_SRI VARCHAR2(500),
    ESTADO_CONTRIBUYENTE VARCHAR2(50),
    TIPO_CONTRIBUYENTE VARCHAR2(100),
    OBLIGADO_CONTABILIDAD VARCHAR2(2),
    AGENTE_RETENCION VARCHAR2(2),
    CONTRIBUYENTE_ESPECIAL VARCHAR2(2),
    FECHA_INICIO_ACTIVIDADES DATE,
    CIIU_PRINCIPAL VARCHAR2(255),
    PROVINCIA_PRINCIPAL VARCHAR2(100),
    CANTON_PRINCIPAL VARCHAR2(100),
    NUMERO_ESTABLECIMIENTOS NUMBER,
    NUMERO_PROVINCIAS NUMBER
);

-- 1.2 Directorio Superintendencia de Compañías (SCVS)
CREATE TABLE SCVS_DIRECTORIO (
    EXPEDIENTE VARCHAR2(20) PRIMARY KEY,
    RUC VARCHAR2(13),
    NOMBRE VARCHAR2(500)
);

-- 1.3 Histórico Financiero Ranking SCVS
CREATE TABLE SCVS_RANKING_RESUMEN (
    EXPEDIENTE VARCHAR2(20),
    ANIO NUMBER,
    INGRESOS NUMBER,
    EMPLEADOS NUMBER,
    ACTIVOS NUMBER,
    PATRIMONIO NUMBER,
    UTILIDAD NUMBER,
    CONSTRAINT PK_SCVS_RANKING PRIMARY KEY (EXPEDIENTE, ANIO)
);

-- ====================================================================
-- 2. TABLAS DEL MODELO K-MEANS B2B
-- ====================================================================

-- 2.1 Golden Record (Master Único)
CREATE TABLE ML_EMPRESAS_MASTER (
    RUC VARCHAR2(13) PRIMARY KEY,
    RAZON_SOCIAL VARCHAR2(255),
    RAZON_SOCIAL_NORM VARCHAR2(255),
    PAIS_EMPRESA VARCHAR2(100),
    SEDE_ECUADOR VARCHAR2(10),
    N_APARICIONES NUMBER,
    FUENTES VARCHAR2(4000)
);

-- 2.2 Golden Record (Alias Múltiples)
CREATE TABLE ML_EMPRESAS_ALIAS_GOLDEN_RECORD (
    RUC VARCHAR2(13),
    NOMBRE_ORIGINAL VARCHAR2(255),
    NOMBRE_ORIGINAL_NORM VARCHAR2(255),
    CONSTRAINT PK_ALIAS PRIMARY KEY (RUC, NOMBRE_ORIGINAL)
);

-- 2.3 Features Capa 1
CREATE TABLE ML_FEATURES_CAPA1 (
    RUC VARCHAR2(13) PRIMARY KEY,
    NAME_NORM VARCHAR2(255),
    TIPO_SOCIEDAD NUMBER,
    OBLIGADO_CONTABILIDAD NUMBER,
    ES_AGENTE_RETENCION NUMBER,
    ES_CONTRIBUYENTE_ESPECIAL NUMBER,
    ESTADO_ACTIVO NUMBER,
    ANTIGUEDAD_ANOS NUMBER,
    SECTOR_CIIU_MACRO VARCHAR2(50),
    REGION VARCHAR2(50)
);

-- 2.4 Features Capa 2
CREATE TABLE ML_FEATURES_CAPA2 (
    RUC VARCHAR2(13),
    ANIO NUMBER,
    NAME_NORM VARCHAR2(255),
    TIPO_SOCIEDAD NUMBER,
    OBLIGADO_CONTABILIDAD NUMBER,
    ES_AGENTE_RETENCION NUMBER,
    ES_CONTRIBUYENTE_ESPECIAL NUMBER,
    ESTADO_ACTIVO NUMBER,
    ANTIGUEDAD_ANOS NUMBER,
    SECTOR_CIIU_MACRO VARCHAR2(50),
    REGION VARCHAR2(50),
    LOG_EMPLEADOS NUMBER,
    LOG_INGRESOS NUMBER,
    LOG_ACTIVOS NUMBER,
    LIQUIDEZ_CORRIENTE NUMBER,
    MARGEN_OPERACIONAL NUMBER,
    CONSTRAINT PK_FEATURES_C2 PRIMARY KEY (RUC, ANIO)
);

-- 2.5 Labels Capa 1
CREATE TABLE ML_LABELS_CAPA1 (
    RUC VARCHAR2(13) PRIMARY KEY,
    SOURCE_LABEL VARCHAR2(50),
    SOURCE_WINNER VARCHAR2(50),
    ES_CLIENTE_FPA NUMBER
);

-- 2.6 Labels Capa 2
CREATE TABLE ML_LABELS_CAPA2 (
    RUC VARCHAR2(13),
    ANIO NUMBER,
    SOURCE_LABEL VARCHAR2(50),
    SOURCE_WINNER VARCHAR2(50),
    ES_CLIENTE_FPA NUMBER,
    CONSTRAINT PK_LABELS_C2 PRIMARY KEY (RUC, ANIO)
);

-- 2.7 Clusters Capa 1
CREATE TABLE ML_CLUSTERS_CAPA1 (
    RUC VARCHAR2(13) PRIMARY KEY,
    CLUSTER_ID NUMBER,
    SEGMENTO VARCHAR2(255)
);

-- 2.8 Clusters Capa 2
CREATE TABLE ML_CLUSTERS_CAPA2 (
    RUC VARCHAR2(13),
    ANIO NUMBER,
    CLUSTER_ID NUMBER,
    SEGMENTO VARCHAR2(255),
    CONSTRAINT PK_CLUSTERS_C2 PRIMARY KEY (RUC, ANIO)
);

-- 2.9 Validación Externa Capa 1
CREATE TABLE ML_VALIDACION_CAPA1 (
    CLUSTER_ID NUMBER PRIMARY KEY,
    SEGMENTO VARCHAR2(255),
    N NUMBER,
    CLIENTES_FPA NUMBER,
    TASA_CLIENTES NUMBER,
    VS_BASE NUMBER
);

-- 2.10 Validación Externa Capa 2
CREATE TABLE ML_VALIDACION_CAPA2 (
    CLUSTER_ID NUMBER PRIMARY KEY,
    SEGMENTO VARCHAR2(255),
    N NUMBER,
    CLIENTES_FPA NUMBER,
    TASA_CLIENTES NUMBER,
    VS_BASE NUMBER
);

-- 2.11 Concordancia ARI
CREATE TABLE ML_CONCORDANCIA_ARI (
    COMPARACION VARCHAR2(100) PRIMARY KEY,
    N_EMPRESAS_COMUNES NUMBER,
    ARI NUMBER
);

-- ====================================================================
-- 3. ÍNDICES (OPTMIZACIÓN APEX)
-- ====================================================================

-- Índices en Golden Record
CREATE INDEX IDX_MASTER_RS_NORM ON ML_EMPRESAS_MASTER(RAZON_SOCIAL_NORM);
CREATE INDEX IDX_ALIAS_RUC ON ML_EMPRESAS_ALIAS_GOLDEN_RECORD(RUC);

-- Índices en Fuentes Oficiales
CREATE INDEX IDX_SCVS_DIR_RUC ON SCVS_DIRECTORIO(RUC);

-- Índices en Clusters
CREATE INDEX IDX_C1_CLUSTER ON ML_CLUSTERS_CAPA1(CLUSTER_ID);
CREATE INDEX IDX_C2_CLUSTER ON ML_CLUSTERS_CAPA2(CLUSTER_ID);

-- ====================================================================
-- 4. VISTAS PARA DASHBOARDS APEX
-- ====================================================================

-- 4.1 Vista Principal Capa 1
CREATE OR REPLACE VIEW VW_EMPRESAS_CLUSTER_CAPA1 AS
SELECT 
    g.RUC,
    g.RAZON_SOCIAL,
    g.PAIS_EMPRESA,
    c.CLUSTER_ID,
    c.SEGMENTO,
    l.ES_CLIENTE_FPA,
    f.SECTOR_CIIU_MACRO,
    f.REGION,
    f.ANTIGUEDAD_ANOS,
    f.TIPO_SOCIEDAD
FROM ML_EMPRESAS_MASTER g
JOIN ML_CLUSTERS_CAPA1 c ON g.RUC = c.RUC
JOIN ML_FEATURES_CAPA1 f ON g.RUC = f.RUC
JOIN ML_LABELS_CAPA1 l ON g.RUC = l.RUC;

-- 4.2 Vista Principal Capa 2
CREATE OR REPLACE VIEW VW_EMPRESAS_CLUSTER_CAPA2 AS
SELECT 
    g.RUC,
    g.RAZON_SOCIAL,
    c.CLUSTER_ID,
    c.SEGMENTO,
    l.ES_CLIENTE_FPA,
    f.ANIO,
    f.SECTOR_CIIU_MACRO,
    f.REGION,
    f.LOG_EMPLEADOS,
    f.LOG_INGRESOS,
    f.LOG_ACTIVOS
FROM ML_EMPRESAS_MASTER g
JOIN ML_CLUSTERS_CAPA2 c ON g.RUC = c.RUC AND c.ANIO = (SELECT MAX(ANIO) FROM ML_CLUSTERS_CAPA2 WHERE RUC = g.RUC)
JOIN ML_FEATURES_CAPA2 f ON c.RUC = f.RUC AND c.ANIO = f.ANIO
JOIN ML_LABELS_CAPA2 l ON c.RUC = l.RUC AND c.ANIO = l.ANIO;

-- 4.3 Vista Resumen Capa 1
CREATE OR REPLACE VIEW VW_RESUMEN_CLUSTER_CAPA1 AS
SELECT 
    CLUSTER_ID,
    SEGMENTO,
    COUNT(RUC) AS TOTAL_EMPRESAS,
    SUM(ES_CLIENTE_FPA) AS TOTAL_CLIENTES_FPA,
    ROUND(SUM(ES_CLIENTE_FPA) / COUNT(RUC) * 100, 2) AS TASA_PENETRACION_PCT
FROM VW_EMPRESAS_CLUSTER_CAPA1
GROUP BY CLUSTER_ID, SEGMENTO;

-- 4.4 Vista Resumen Capa 2
CREATE OR REPLACE VIEW VW_RESUMEN_CLUSTER_CAPA2 AS
SELECT 
    CLUSTER_ID,
    SEGMENTO,
    COUNT(RUC) AS TOTAL_EMPRESAS,
    ROUND(AVG(LOG_INGRESOS), 2) AS PROMEDIO_LOG_INGRESOS,
    ROUND(AVG(LOG_EMPLEADOS), 2) AS PROMEDIO_LOG_EMPLEADOS,
    SUM(ES_CLIENTE_FPA) AS TOTAL_CLIENTES_FPA
FROM VW_EMPRESAS_CLUSTER_CAPA2
GROUP BY CLUSTER_ID, SEGMENTO;

-- 4.5 Vista de Validación Directa Capa 1
CREATE OR REPLACE VIEW VW_VALIDACION_EXTERNA_CAPA1 AS
SELECT * FROM ML_VALIDACION_CAPA1;

-- 4.6 Vista de Validación Directa Capa 2
CREATE OR REPLACE VIEW VW_VALIDACION_EXTERNA_CAPA2 AS
SELECT * FROM ML_VALIDACION_CAPA2;

-- 4.7 Vista Consulta 360 RUC (Uniendo Golden, SRI, SCVS, Clusters y Prioridad)
CREATE OR REPLACE VIEW VW_CONSULTA_RUC_SRI AS
WITH RANKING_ACTUAL AS (
    SELECT EXPEDIENTE, ANIO, INGRESOS, EMPLEADOS,
           ROW_NUMBER() OVER (PARTITION BY EXPEDIENTE ORDER BY ANIO DESC) as rn
    FROM SCVS_RANKING_RESUMEN
),
LATEST_CLUSTER_CAPA2 AS (
    SELECT RUC, SEGMENTO,
           ROW_NUMBER() OVER (PARTITION BY RUC ORDER BY ANIO DESC) as rn
    FROM ML_CLUSTERS_CAPA2
)
SELECT 
    g.RUC,
    g.RAZON_SOCIAL AS RAZON_SOCIAL_GOLDEN,
    sri.ESTADO_CONTRIBUYENTE,
    sri.TIPO_CONTRIBUYENTE,
    sri.CIIU_PRINCIPAL,
    sri.PROVINCIA_PRINCIPAL,
    c1.SEGMENTO AS SEGMENTO_CAPA1,
    c2.SEGMENTO AS SEGMENTO_CAPA2,
    l1.ES_CLIENTE_FPA,
    scvs.EXPEDIENTE,
    rnk.INGRESOS,
    rnk.EMPLEADOS,
    rnk.ANIO AS ANIO_FINANCIERO,
    -- Lógica de Priorización (Clustering a Acción Comercial)
    CASE 
        WHEN l1.ES_CLIENTE_FPA = 1 THEN 'Cliente Actual'
        WHEN c2.SEGMENTO = 'Grandes consolidadas' OR c1.SEGMENTO IN ('Industriales', 'Comercio maduro') THEN 'Foco Alto'
        WHEN c2.SEGMENTO = 'Medianas/recientes' THEN 'Foco Medio'
        WHEN c1.SEGMENTO IS NOT NULL THEN 'Foco Bajo'
        ELSE 'Sin Clasificar'
    END AS NIVEL_PRIORIDAD
FROM ML_EMPRESAS_MASTER g
LEFT JOIN SRI_RUC_EMPRESAS_RESUMEN sri ON g.RUC = sri.RUC
LEFT JOIN ML_CLUSTERS_CAPA1 c1 ON g.RUC = c1.RUC
LEFT JOIN ML_LABELS_CAPA1 l1 ON g.RUC = l1.RUC
LEFT JOIN LATEST_CLUSTER_CAPA2 c2 ON g.RUC = c2.RUC AND c2.rn = 1
LEFT JOIN SCVS_DIRECTORIO scvs ON g.RUC = scvs.RUC
LEFT JOIN RANKING_ACTUAL rnk ON scvs.EXPEDIENTE = rnk.EXPEDIENTE AND rnk.rn = 1;
